CREATE TABLE wall_content (
    id INT AUTO_INCREMENT PRIMARY KEY,
    wall_id INT NOT NULL COMMENT '主分类ID',
    sub_id INT NOT NULL COMMENT '子分类ID',
    status TINYINT DEFAULT 0 COMMENT '0审核中/1正常/2锁定',
    visibility TINYINT DEFAULT 2 COMMENT '可见性:0仅自己/1好友/2所有人',
    user_id INT NOT NULL COMMENT '发布者ID',
    ip VARCHAR(45) COMMENT '发布IP',
    ip_location VARCHAR(100) COMMENT 'IP归属地',
    topic VARCHAR(100) NOT NULL COMMENT '标题',
    content TEXT NOT NULL COMMENT '正文内容',
    publish_time DATETIME NOT NULL COMMENT '发布时间',
    edit_time DATETIME COMMENT '最后编辑时间',
    like_count INT DEFAULT 0 COMMENT '点赞数',
    comment_count INT DEFAULT 0 COMMENT '评论数',
    collect_count INT DEFAULT 0 COMMENT '收藏数',
    forward_count INT DEFAULT 0 COMMENT '转发数',
    is_anonymous TINYINT DEFAULT 0 COMMENT '是否匿名发布(0否/1是)',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (wall_id) REFERENCES wall_sort(id) ON DELETE CASCADE,
    FOREIGN KEY (sub_id) REFERENCES wall_subsort(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='墙内容主表';