CREATE TABLE wall_sort (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '分类名称',
    status TINYINT DEFAULT 0 COMMENT '0正常/1停用/2审核中'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='墙主分类';